@base_url = http://127.0.0.1:5000


GET {{base_url}}/users/4
Content-Type: application/json

### СОЗДАЕМ ПОЛЬЗОВАТЕЛЯ

POST {{base_url}}/users/
Content-Type: application/json

{
    "name": "user1",
    "password": "123456789"
}

###

PATCH {{base_url}}/users/4
Content-Type: application/json

{
    "name": "user4",
    "password": "123456789"
}

###

DELETE {{base_url}}/users/2
Content-Type: application/json

###
# ЛОГИНИМСЯ ~~~~~~~~~~~~~~~~~~~~~~~~~~
POST {{base_url}}/login
Content-Type: application/json
Accept-Encoding: "utf-8"

{
    "username": "user2",
    "password": "123456789"
}

###
# РАЗМЕЩАЕМ ОБЪЯВЛЕНИЕ
POST {{base_url}}/ads/
Content-Type: application/json

{
    "headline": "Headline1",
    "description": "Text of the texts"
}

###

GET {{base_url}}/ads/4
Content-Type: application/json; charset=utf-8

###

PATCH {{base_url}}/ads/4
Content-Type: application/json; charset=utf-8

{
    "headline": "Headline2",
    "description": "Replaced text"
}

###

DELETE {{base_url}}/ads/4
Content-Type: application/json
